version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rentopia-db
    environment:
      POSTGRES_USER: rentopia
      POSTGRES_PASSWORD: rentopia_password
      POSTGRES_DB: rentopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rentopia -d rentopia"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: rentopia-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
